// test_aura_core.cpp - validates the native core against the Python reference.
//
// Build & run on any host (no Android toolchain needed):
//     g++ -std=c++17 -O2 -I.. test_aura_core.cpp ../aura_core.cpp -o test_aura_core
//     ./test_aura_core
//
// The expected values in the cross-check tests are produced by
// `edge-agent/aura/*` and regenerated by `tools/generate_native_fixtures.py`.

#include "../aura_core.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <random>
#include <string>
#include <vector>

namespace {

int g_failures = 0;
int g_checks = 0;

void check(bool condition, const std::string& what) {
    ++g_checks;
    if (!condition) {
        ++g_failures;
        std::printf("  FAIL: %s\n", what.c_str());
    }
}

void checkNear(float actual, float expected, float tolerance, const std::string& what) {
    ++g_checks;
    if (!(std::fabs(actual - expected) <= tolerance)) {
        ++g_failures;
        std::printf("  FAIL: %s (got %.6f, expected %.6f +/- %.6f)\n",
                    what.c_str(), actual, expected, tolerance);
    }
}

void section(const char* name) { std::printf("\n== %s ==\n", name); }

// ---------------------------------------------------------------------
void testLinearAlgebra() {
    section("linear algebra");
    const float A[6] = {1, 2, 3, 4, 5, 6};   // 2x3
    const float x[3] = {1, 1, 1};
    float y[2] = {0, 0};
    aura::matVec(A, x, y, 2, 3);
    checkNear(y[0], 6.0f, 1e-6f, "matVec row 0");
    checkNear(y[1], 15.0f, 1e-6f, "matVec row 1");

    const float v[2] = {1, 1};
    float out[3] = {0, 0, 0};
    aura::matTVec(A, v, out, 2, 3);
    checkNear(out[0], 5.0f, 1e-6f, "matTVec col 0");
    checkNear(out[2], 9.0f, 1e-6f, "matTVec col 2");

    const float a[4] = {1, 2, 3, 4};
    checkNear(aura::dot(a, a, 4), 30.0f, 1e-6f, "dot");
    checkNear(aura::norm2(a, 4), std::sqrt(30.0f), 1e-6f, "norm2");
}

// ---------------------------------------------------------------------
void testSoftThreshold() {
    section("soft threshold");
    float x[5] = {-2.0f, -0.4f, 0.0f, 0.4f, 2.0f};
    aura::softThreshold(x, 5, 0.5f, false);
    checkNear(x[0], -1.5f, 1e-6f, "negative shrinks toward zero");
    checkNear(x[1], 0.0f, 1e-6f, "below threshold clamps");
    checkNear(x[4], 1.5f, 1e-6f, "positive shrinks toward zero");

    float y[3] = {-2.0f, 1.0f, 3.0f};
    aura::softThreshold(y, 3, 0.5f, true);
    check(y[0] == 0.0f, "non-negative projection");
    checkNear(y[2], 2.5f, 1e-6f, "non-negative keeps positives");
}

// ---------------------------------------------------------------------
std::vector<float> ringNodes(int count, float cx, float cy, float radius) {
    std::vector<float> nodes(static_cast<size_t>(count) * 2);
    for (int i = 0; i < count; ++i) {
        const float angle = 2.0f * 3.14159265358979f * i / count;
        nodes[2 * i] = cx + radius * std::cos(angle);
        nodes[2 * i + 1] = cy + radius * std::sin(angle);
    }
    return nodes;
}

void testRti() {
    section("RTI / FISTA");
    const int nodeCount = 12;
    const int nx = 24, ny = 24;
    const float resolution = 0.25f;
    auto nodes = ringNodes(nodeCount, 3.0f, 3.0f, 3.2f);
    auto W = aura::buildWeightMatrix(nodes.data(), nodeCount, 0.0f, 0.0f,
                                     resolution, nx, ny);
    const int links = nodeCount * (nodeCount - 1) / 2;
    const int voxels = nx * ny;
    check(static_cast<int>(W.size()) == links * voxels, "weight matrix size");

    // The Lipschitz constant must be well below the naive Frobenius bound.
    const float L = aura::powerIterationLipschitz(W.data(), links, voxels);
    double frob = 0.0;
    for (float value : W) frob += static_cast<double>(value) * value;
    check(L > 0.0f && L < static_cast<float>(frob),
          "power iteration is tighter than ||W||_F^2");

    // Ground truth: a single occupied voxel at (2.0, 4.0).
    const int ti = static_cast<int>(2.0f / resolution);
    const int tj = static_cast<int>(4.0f / resolution);
    std::vector<float> truth(voxels, 0.0f);
    truth[tj * nx + ti] = 1.0f;

    std::vector<float> y(links, 0.0f);
    aura::matVec(W.data(), truth.data(), y.data(), links, voxels);
    std::mt19937 rng(2);
    std::normal_distribution<float> noise(0.0f, 0.01f);
    for (float& value : y) value += noise(rng);

    auto result = aura::reconstructL1Fista(W.data(), y.data(), links, voxels,
                                           0.05f, 300, 1e-6f, true, L);
    check(result.iterations > 0, "FISTA ran");

    int peak = 0;
    for (int i = 1; i < voxels; ++i) {
        if (result.image[i] > result.image[peak]) peak = i;
    }
    const float px = (peak % nx + 0.5f) * resolution;
    const float py = (peak / nx + 0.5f) * resolution;
    const float error = std::hypot(px - 2.0f, py - 4.0f);
    std::printf("  reconstructed peak at (%.2f, %.2f), error %.3f m\n", px, py, error);
    check(error < 0.6f, "FISTA localises the target within 0.6 m");

    for (float value : result.image) check(value >= 0.0f, "non-negativity holds");

    // L1 must be sparser than the Tikhonov baseline.
    auto l2 = aura::reconstructTikhonov(W.data(), y.data(), links, voxels, 0.1f);
    float l1Peak = 0.0f, l2Peak = 0.0f;
    for (int i = 0; i < voxels; ++i) {
        l1Peak = std::max(l1Peak, result.image[i]);
        l2Peak = std::max(l2Peak, l2[i]);
    }
    int l1nnz = 0, l2nnz = 0;
    for (int i = 0; i < voxels; ++i) {
        if (result.image[i] > 0.05f * l1Peak) ++l1nnz;
        if (l2[i] > 0.05f * l2Peak) ++l2nnz;
    }
    std::printf("  support: L1 %d voxels vs Tikhonov %d voxels\n", l1nnz, l2nnz);
    check(l1nnz < l2nnz, "L1 solution is sparser than L2");
}

// ---------------------------------------------------------------------
void testFft() {
    section("FFT");
    const int n = 64;
    std::vector<aura::Complex> data(n);
    for (int i = 0; i < n; ++i) {
        const float t = static_cast<float>(i) / n;
        data[i] = aura::Complex(std::cos(2.0f * 3.14159265f * 4.0f * t), 0.0f);
    }
    auto original = data;
    aura::fftInPlace(data.data(), n, false);
    int peak = 0;
    for (int i = 1; i < n / 2; ++i) {
        if (std::abs(data[i]) > std::abs(data[peak])) peak = i;
    }
    check(peak == 4, "FFT finds the 4-cycle tone");

    aura::fftInPlace(data.data(), n, true);
    float maxError = 0.0f;
    for (int i = 0; i < n; ++i) {
        maxError = std::max(maxError, std::abs(data[i] - original[i]));
    }
    checkNear(maxError, 0.0f, 1e-4f, "inverse FFT round-trip");
}

// ---------------------------------------------------------------------
void testPassiveRadar() {
    section("passive radar");
    const int n = 16384;
    const float fs = 2.4e6f;
    std::mt19937 rng(7);
    std::uniform_int_distribution<int> bit(0, 1);

    std::vector<aura::Complex> ref(n);
    for (int i = 0; i < n; ++i) {
        ref[i] = aura::Complex(bit(rng) ? 1.0f : -1.0f, bit(rng) ? 1.0f : -1.0f);
    }

    const int delay = 15;
    const float doppler = 400.0f;   // resolvable: 16384/2.4e6 = 6.8 ms -> 146 Hz cells
    const float directGain = 300.0f;
    std::vector<aura::Complex> surv(n);
    for (int i = 0; i < n; ++i) {
        aura::Complex echo(0.0f, 0.0f);
        if (i >= delay) {
            const float phase = 2.0f * 3.14159265f * doppler * i / fs;
            echo = 0.05f * ref[i - delay] * aura::Complex(std::cos(phase), std::sin(phase));
        }
        surv[i] = directGain * ref[i] + echo;
    }

    auto clean = aura::ecaCancel(surv.data(), ref.data(), n, 16);
    const float suppression = aura::cancellationRatioDb(surv.data(), clean.data(), n);
    std::printf("  direct-path cancellation: %.1f dB\n", suppression);
    check(suppression > 25.0f, "ECA removes the direct path");

    auto map = aura::computeCaf(clean.data(), ref.data(), n, fs, 32, 64);
    check(map.rangeBins == 32, "range bin count");
    check(map.dopplerBins == 64, "doppler bin count (power of two)");

    int bestR = 0, bestD = 0;
    float best = -1.0f;
    for (int d = 0; d < map.dopplerBins; ++d) {
        for (int r = 0; r < map.rangeBins; ++r) {
            const float value = map.magnitude[static_cast<size_t>(d) * map.rangeBins + r];
            if (value > best) { best = value; bestR = r; bestD = d; }
        }
    }
    const float batchRate = fs / (n / map.dopplerBins);
    const float dopplerHz = (bestD - map.dopplerBins / 2) * batchRate / map.dopplerBins;
    std::printf("  CAF peak: range bin %d, doppler %.1f Hz\n", bestR, dopplerHz);
    check(bestR == delay, "CAF recovers the delay bin");
    checkNear(dopplerHz, doppler, 200.0f, "CAF recovers the Doppler shift");

    // CFAR on a synthetic map
    std::vector<float> magnitude(40 * 40, 1.0f);
    magnitude[20 * 40 + 20] = 100.0f;
    auto mask = aura::cfar2d(magnitude.data(), 40, 40, 2, 2, 6, 6, 15.0f);
    check(mask[20 * 40 + 20] == 1, "CFAR detects the peak");
    int detections = 0;
    for (uint8_t m : mask) detections += m;
    check(detections < 10, "CFAR does not flood the map");
}

// ---------------------------------------------------------------------
void testEkf() {
    section("EKF");
    checkNear(aura::wrapPi(3.0f * 3.14159265f), 3.14159265f, 1e-4f, "wrapPi 3pi");
    checkNear(aura::wrapPi(0.5f), 0.5f, 1e-6f, "wrapPi identity");

    // stationary filter must not drift
    {
        aura::ExtendedKalmanFilter ekf;
        const float gyro[3] = {0.0f, 0.0f, 0.0f};
        const float accel[3] = {0.0f, 0.0f, 9.80665f};
        for (int i = 0; i < 400; ++i) {
            ekf.predict(gyro, accel, 0.05f);
            ekf.updateZeroVelocity();
        }
        const float* x = ekf.state();
        const float drift = std::sqrt(x[0] * x[0] + x[1] * x[1] + x[2] * x[2]);
        std::printf("  stationary drift after 20 s: %.4f m\n", drift);
        check(drift < 0.05f, "no drift while stationary");
    }

    // constant acceleration: s = 0.5 a t^2
    {
        aura::ExtendedKalmanFilter ekf;
        const float gyro[3] = {0.0f, 0.0f, 0.0f};
        const float accel[3] = {1.0f, 0.0f, 9.80665f};
        for (int i = 0; i < 200; ++i) ekf.predict(gyro, accel, 0.01f);
        const float* x = ekf.state();
        checkNear(x[0], 2.0f, 0.06f, "position after 2 s at 1 m/s^2");
        checkNear(x[3], 2.0f, 0.06f, "velocity after 2 s at 1 m/s^2");
    }

    // UWB trilateration
    {
        aura::ExtendedKalmanFilter ekf;
        const float anchors[4][3] = {{0.0f, 0.0f, 2.4f},
                                     {12.0f, 0.0f, 2.4f},
                                     {12.0f, 9.0f, 2.4f},
                                     {0.0f, 9.0f, 2.4f}};
        const float truth[3] = {6.0f, 4.0f, 1.4f};
        for (int it = 0; it < 120; ++it) {
            for (const auto& anchor : anchors) {
                const float d = std::sqrt(std::pow(truth[0] - anchor[0], 2.0f) +
                                          std::pow(truth[1] - anchor[1], 2.0f) +
                                          std::pow(truth[2] - anchor[2], 2.0f));
                ekf.updateUwbRange(anchor, d, 0.05f);
            }
            ekf.updateAltitude(1.4f, 0.1f);
        }
        const float* x = ekf.state();
        const float error = std::hypot(x[0] - truth[0], x[1] - truth[1]);
        std::printf("  UWB trilateration error: %.4f m\n", error);
        check(error < 0.2f, "UWB converges to the true position");
    }

    // the LiDAR update must leave the altitude alone
    {
        aura::ExtendedKalmanFilter ekf;
        const float before = ekf.state()[2];
        for (int i = 0; i < 20; ++i) ekf.updateLidarPose(2.0f, 3.0f, 0.5f, 0.06f, 0.10f);
        checkNear(ekf.state()[2], before, 1e-5f, "scan match does not touch z");
        checkNear(ekf.state()[0], 2.0f, 0.1f, "scan match pulls x");
        checkNear(aura::wrapPi(ekf.state()[8] - 0.5f), 0.0f, 0.1f, "scan match pulls yaw");
    }

    // covariance stays finite and symmetric under a random workload
    {
        aura::ExtendedKalmanFilter ekf;
        std::mt19937 rng(3);
        std::normal_distribution<float> n01(0.0f, 1.0f);
        for (int i = 0; i < 300; ++i) {
            const float gyro[3] = {0.05f * n01(rng), 0.05f * n01(rng), 0.05f * n01(rng)};
            const float accel[3] = {0.1f * n01(rng), 0.1f * n01(rng), 9.80665f + 0.1f * n01(rng)};
            ekf.predict(gyro, accel, 0.05f);
            const float pos[3] = {n01(rng), n01(rng), 1.4f};
            ekf.updatePosition(pos, 0.5f);
        }
        const float* P = ekf.covariance();
        bool finite = true, symmetric = true;
        for (int i = 0; i < aura::kStateDim; ++i) {
            for (int j = 0; j < aura::kStateDim; ++j) {
                const float value = P[i * aura::kStateDim + j];
                if (!std::isfinite(value)) finite = false;
                if (std::fabs(value - P[j * aura::kStateDim + i]) > 1e-4f) symmetric = false;
            }
            if (P[i * aura::kStateDim + i] <= 0.0f) finite = false;
        }
        check(finite, "covariance stays finite and positive on the diagonal");
        check(symmetric, "covariance stays symmetric");
    }

    // quaternion must be unit length
    {
        aura::ExtendedKalmanFilter ekf;
        const float gyro[3] = {0.1f, -0.05f, 0.2f};
        const float accel[3] = {0.3f, 0.1f, 9.6f};
        for (int i = 0; i < 50; ++i) ekf.predict(gyro, accel, 0.02f);
        float q[4];
        ekf.quaternion(q);
        const float length = std::sqrt(q[0] * q[0] + q[1] * q[1] + q[2] * q[2] + q[3] * q[3]);
        checkNear(length, 1.0f, 1e-4f, "quaternion is normalised");
    }
}

// ---------------------------------------------------------------------
void testVoxelCodec() {
    section("voxel RLE codec");
    const int size = 16;
    const int total = size * size * size;
    std::vector<uint16_t> intensity(total, 0);
    std::vector<uint8_t> label(total, 0);
    intensity[100] = 40000; label[100] = 2;
    intensity[2000] = 12345; label[2000] = 3;

    auto blob = aura::encodeChunk(intensity.data(), label.data(), size);
    std::printf("  encoded %d voxels into %zu bytes\n", total, blob.size());
    check(blob.size() < 100, "sparse chunk compresses well");
    check(blob[0] == 'A' && blob[1] == 'V' && blob[2] == 'X' && blob[3] == '1', "magic header");

    std::vector<uint16_t> outI(total, 0);
    std::vector<uint8_t> outL(total, 0);
    check(aura::decodeChunk(blob.data(), blob.size(), outI.data(), outL.data(), size),
          "decode succeeds");
    bool identical = true;
    for (int i = 0; i < total; ++i) {
        if (outI[i] != intensity[i] || outL[i] != label[i]) { identical = false; break; }
    }
    check(identical, "RLE round-trip is lossless");

    const uint8_t garbage[9] = {'X', 'X', 'X', 'X', 16, 0, 0, 0, 0};
    check(!aura::decodeChunk(garbage, sizeof(garbage), outI.data(), outL.data(), size),
          "bad magic is rejected");
}

}  // namespace

int main() {
    std::printf("AURA 6.0 native core test suite\n");
    testLinearAlgebra();
    testSoftThreshold();
    testRti();
    testFft();
    testPassiveRadar();
    testEkf();
    testVoxelCodec();

    std::printf("\n----------------------------------------\n");
    std::printf("%d checks, %d failures\n", g_checks, g_failures);
    return g_failures == 0 ? 0 : 1;
}
