#!/usr/bin/env python3
"""Extract the project's reference documents into reviewable text.

The Aura design rests on a stack of vendor and research documents (Honeywell
CT45P specifications, BLE/UWB analyses, through-wall sensing studies, SDR
notes). Those PDFs are large and are deliberately NOT committed: the repository
would balloon and most of them are third-party material. This tool turns them
into plain text under `docs/reference/` (gitignored) so their claims can be
checked against the implementation.

The point is auditability. Several numbers in this codebase -- the CT45P's
API level, the USB VIDs, the DWM3000 line format, the achievable range
resolution -- came from these documents, and a claim nobody can re-check is
indistinguishable from one that was invented.

Usage:
    tools/ingest-reference-docs.py --src ~/uploads
    tools/ingest-reference-docs.py --src ~/uploads --grep "CT45P" --grep "UWB"
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    from pypdf import PdfReader
except ImportError:  # pragma: no cover
    print("error: pip install pypdf", file=sys.stderr)
    raise SystemExit(2)


def extract_pdf(path: Path) -> tuple[str, int]:
    reader = PdfReader(str(path))
    pages = []
    for i, page in enumerate(reader.pages):
        try:
            pages.append(f"\n\n===== [page {i + 1}] =====\n" + (page.extract_text() or ""))
        except Exception as exc:  # a damaged page must not lose the rest
            pages.append(f"\n\n===== [page {i + 1}: extraction failed: {exc}] =====\n")
    return "".join(pages), len(reader.pages)


def slug(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-")
    return re.sub(r"-{2,}", "-", s)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, help="directory holding the source documents")
    ap.add_argument("--out", default="docs/reference", help="where to write extracted text")
    ap.add_argument("--grep", action="append", default=[],
                    help="report every line matching this term (repeatable)")
    args = ap.parse_args()

    src = Path(args.src).expanduser()
    if not src.is_dir():
        print(f"error: {src} is not a directory", file=sys.stderr)
        return 2

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    docs = sorted(
        p for p in src.iterdir()
        if p.is_file() and p.suffix.lower() in {".pdf", ".txt", ".html", ".htm", ".md"}
    )
    if not docs:
        print(f"no documents found in {src}", file=sys.stderr)
        return 1

    index: list[tuple[str, int, int]] = []
    hits: dict[str, list[tuple[str, str]]] = {t: [] for t in args.grep}

    for doc in docs:
        try:
            if doc.suffix.lower() == ".pdf":
                text, pages = extract_pdf(doc)
            else:
                text = doc.read_text(encoding="utf-8", errors="replace")
                pages = 0
                if doc.suffix.lower() in {".html", ".htm"}:
                    text = re.sub(r"<script.*?</script>|<style.*?</style>", " ", text,
                                  flags=re.S | re.I)
                    text = re.sub(r"<[^>]+>", " ", text)
                    text = re.sub(r"[ \t]{2,}", " ", text)
        except Exception as exc:
            print(f"  !! {doc.name}: {exc}", file=sys.stderr)
            continue

        target = out / (slug(doc.stem) + ".txt")
        target.write_text(text, encoding="utf-8")
        index.append((doc.name, pages, len(text)))
        print(f"  {doc.name} -> {target.name} ({pages} pages, {len(text):,} chars)")

        for term in args.grep:
            for line in text.splitlines():
                if term.lower() in line.lower():
                    clean = line.strip()
                    if clean:
                        hits[term].append((doc.name, clean[:300]))

    (out / "INDEX.md").write_text(
        "# Extracted reference documents\n\n"
        "Generated by `tools/ingest-reference-docs.py`. Not committed.\n\n"
        "| document | pages | characters |\n|---|---:|---:|\n"
        + "".join(f"| {n} | {p or '-'} | {c:,} |\n" for n, p, c in index),
        encoding="utf-8",
    )

    for term, found in hits.items():
        print(f"\n=== '{term}': {len(found)} matching lines ===")
        for name, line in found[:40]:
            print(f"  [{name}] {line}")
        if len(found) > 40:
            print(f"  ... and {len(found) - 40} more")

    print(f"\n{len(index)} documents extracted to {out}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
